# Generated by Django 6.0.1 on 2026-01-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CURSOSREALIZADOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperfilconqueestaactivo', models.IntegerField()),
                ('nombre_curso', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horas', models.IntegerField()),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DATOSPERSONALES',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('perfilactivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EXPERIENCIALABORAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperfilconqueestaactivo', models.IntegerField()),
                ('empresa', models.CharField(max_length=150)),
                ('puesto', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTOSACADEMICOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperfilconqueestaactivo', models.IntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('autores', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTOSLABORALES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperfilconqueestaactivo', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('fecha_entrega', models.DateField()),
                ('tecnologias', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RECONOCIMIENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperfilconqueestaactivo', models.IntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VENTAGARAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('fecha_venta', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
