# Generated by Django 6.0.1 on 2026-01-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CURSOSREALIZADOS',
        ),
        migrations.DeleteModel(
            name='EXPERIENCIALABORAL',
        ),
        migrations.DeleteModel(
            name='PRODUCTOSACADEMICOS',
        ),
        migrations.DeleteModel(
            name='PRODUCTOSLABORALES',
        ),
        migrations.DeleteModel(
            name='RECONOCIMIENTOS',
        ),
        migrations.DeleteModel(
            name='VENTAGARAGE',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='telefono',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'H'), ('M', 'M')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(default=1),
        ),
    ]
