# Generated by Django 6.0.1 on 2026-01-25 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0002_delete_cursosrealizados_delete_experiencialaboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CURSOSREALIZADOS',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activarparaqueseveaenfront', models.IntegerField(default=1)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='EXPERIENCIALABORAL',
            fields=[
                ('idexperiencia', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activarparaqueseveaenfront', models.IntegerField(default=1)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='RECONOCIMIENTOS',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(max_length=50)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.TextField(blank=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=20)),
                ('rutacertificado', models.CharField(blank=True, max_length=200)),
                ('activarparaqueseveaenfront', models.IntegerField(default=1)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
        ),
    ]
