# Generated by Django 6.0.1 on 2026-01-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0003_cursosrealizados_experiencialaboral_reconocimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
    ]
