# Generated by Django 6.0.1 on 2026-01-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0004_alter_datospersonales_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconocimientos',
            name='rutacertificado',
        ),
        migrations.AddField(
            model_name='cursosrealizados',
            name='archivo_certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='archivo_certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
