# Generated by Django 6.0.1 on 2026-01-25 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0005_remove_reconocimientos_rutacertificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCTOSACADEMICOS',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=150)),
                ('tiposproducto', models.CharField(max_length=100)),
                ('fechapublicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('enlace', models.URLField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='productos/')),
                ('activarparaqueseveaenfront', models.IntegerField(default=1)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
        ),
    ]
