# Generated by Django 6.0.1 on 2026-01-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0006_productosacademicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCTOSLABORALES',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('enlace', models.URLField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='productos/')),
                ('activarparaqueseveaenfront', models.IntegerField(default=1)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VENTAS',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('valordelbien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estadoproducto', models.CharField(blank=True, max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ventas/')),
                ('activarparaqueseveaenfront', models.IntegerField(default=1)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
        ),
    ]
