# Generated by Django 6.0.1 on 2026-01-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0007_productoslaborales_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
