# Generated by Django 6.0 on 2026-01-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0008_datospersonales_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_ventas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fechapublicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='estadoproducto',
            field=models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=50),
        ),
    ]
