# Generated by Django 6.0.1 on 2026-01-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0009_datospersonales_mostrar_cursos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
